### ISSUE TITLE
Symbol#to_proc with and_yield not working on JRuby

### ISSUE THREAD

**Issue by xaviershay** [rspec/rspec-mocks#1044]
Discovered by @nerdrew, who is sitting next to me reporting this.

``` ruby
class A
  def self.hello
  end
end

describe do
  it do
    expect(A).to receive(:hello).and_yield(1)
    expect(A.hello(&:to_s)).to eq("1")
  end
end
```

This passes on CRuby 2.2.2, but fails on JRuby 1.7.20.

```
> rspec test_spec.rb 
F

Failures:

  1)  should receive hello(*(any args)) 1 time
     Failure/Error: expect(A.hello(&:to_s)).to eq("1")
       #<A (class)> yielded |1| to block with 
     # ./test_spec.rb:9:in `(root)'

Finished in 0.134 seconds (files took 0.396 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./test_spec.rb:7 #  should receive hello(*(any args)) 1 time
```

My first guess is JRuby optimizing code different to CRuby ... I think `and_yield` should still work in this case. Not sure if this bug is in RSpec or JRuby. cc @headius in case
### Possible different RSpec bug

Shouldn't `A.hello(&:to_s)` return `nil` rather than `"1"`? We only specified `and_yield` on the expectation, not `and_return`...

**Comment by headius** [comment]
Also fails the same way in JRuby 9k HEAD.

**Comment by headius** [comment]
I'm really confused what this is specifying. There's no yield, so how would `and_yield` anything? I see the `&:to_s` getting passed as the block to `A.hello` but should't the `and_yield` fail in any case since `hello` never yields?

**Comment by headius** [comment]
Ok, if I'm reading the code for `and_yield` right, it's a forcing behavior for a mock, making the message always yield a given result. So in this case, the `receive` acts as an expectation, but the `yield` will *always* cause that message reception to yield the given value. It's not part of the expectation.

It passes in MRI because the yield happens, producing `"1"` which matches the expectation. But it's testing rspec, not your code.

Still unsure what the JRuby error is about, though.

**Comment by headius** [comment]
Ok, the error is rspec verifying that the block can accommodate the requested yield arguments. It fails because JRuby does not report proc'ified core methods as `[[:rest]]` so it never gets to the point of trying to yield.

```
[] ~/projects/jruby $ jruby -e 'p proc(&:to_s).parameters'
[]

[] ~/projects/jruby $ rvm ruby-2.2.2 do ruby -e 'p proc(&:to_s).parameters'
[[:rest]]
```

This is a JRuby bug in 1.7 and 9k.

**Comment by xaviershay** [comment]
Thanks for quick reply! Sorry repro was confusing, I agree it's not testing anything :) For context, came across this in code more like:

``` ruby
expect(IO).to receive(:popen).and_yield(double(read: 'hello')))
IO.popen(cmd) {|x| x.read }
```

... which works, but then the block was refactored to `&:read` and the test started failing.

**Comment by xaviershay** [comment]
We (RSpec team) should consider a workaround to not verify arguments if on affected versions of JRuby.

**Comment by headius** [comment]
The fix is simple and I've already pushed a [spec for rubyspec](https://github.com/ruby/rubyspec/commit/26173392adf88f36e516ff2b2816a5c301cec2f5). Fix should be in next releases of JRuby 1.7 and 9k.

**Comment by headius** [comment]
FWIW, Rubinius's output for a `Symbol#to_proc`'s `Proc#parameters` differs from MRI, but it should work ok here:

```
[] ~/projects/rubyspec $ rvm rbx-2.5.8 do ruby ../mspec/bin/mspec run core/symbol/to_proc_spec.rb 
rubinius 2.5.7.c51 (2.1.0 1d60cbe3 2015-07-09 3.5.0 JI) [x86_64-darwin14.0.0]
...F.

1)
Symbol#to_proc produces a proc that always returns [[:rest]] for #parameters FAILED
Expected [[:rest, :args]]
 to equal [[:rest]]
```

**Comment by myronmarston** [comment]
Thanks for the quick fix, @headius!

> Shouldn't `A.hello(&:to_s)` return nil rather than `"1"`? We only specified `and_yield` on the expectation, not `and_return`...

It is slightly odd, but it's intentional behavior.  We have [a spec](https://github.com/rspec/rspec-mocks/blob/master/spec/rspec/mocks/double_spec.rb#L423-L428) for it.  Here's how I think of it.  A stubbed method begins empty:

``` ruby
allow(foo).to receive(:bar)

# equals:

def foo.bar
end
```

...and then when you chain `and_yield`, it adds the yield:


``` ruby
allow(foo).to receive(:bar).and_yield(:bazz)

# equals:

def foo.bar
  yield :bazz
end
```

At this point, the implementation will return whatever the block returns since `yield` is the last statement in the method.  You can override it and have it return something as well if you care:

``` ruby
allow(foo).to receive(:bar).and_yield(:bazz).and_return(:done)

# equals:

def foo.bar
  yield :bazz
  :done
end
```

**Comment by xaviershay** [comment]
> It is slightly odd, but it's intentional behavior.

Fair enough, I don't have strong feelings about it.

**Comment by headius** [comment]
Auditing old issues that mention me...

This example spec passes fine on recent JRuby versions.

**Comment by pirj** [comment]
Thanks @headius !
I guess we can close this.
