### ISSUE TITLE
stub_const overwrites Class definition

### ISSUE THREAD

**Issue by tdeo** [rspec/rspec-mocks#1079]
When using stub_const before the Class containing the constant has been loaded, a module is automatically created with the name.

Here is a minimal working example (on Rails file structure):
`app/models/model.rb`:
```ruby
class Model
  CONST = 10

  def initialize
    puts 'Creating instance'
  end
end
```

`spec/models/model_spec.rb`:
```ruby
require 'rails_helper'

describe 'something' do
  describe 'stub_const' do
    it 'doesn\'t overwrite the class definition' do
      stub_const('Model::CONST', 2)
      Model.new
    end
  end
end
```

And that test fails with:
```
Failures:

  1) something stub_const doesn't overwrite the class definition
     Failure/Error: Model.new
     NoMethodError:
       undefined method `new' for #<Module:0x000000089a8be0>
```

I think in that case the Module or Class should be loaded and an exception raised in case it doesn't exists or the original constant doesn't (The same way using `expect(Class).to receive(:method)` fails if method doesn't exist).

I'm using rspec-mocks 3.3.2 with rails 4.2.3 and haven't tried it with the master branch, but nothing appears in the changelog.

**Comment by myronmarston** [comment]
> When using stub_const before the Class containing the constant has been loaded, a module is automatically created with the name.

This is working by design: since `Model` does not exist, in order to stub `Model::CONST`, RSpec has to create `Model`, but it has no way to know if it should be created as a module or class.  It creates it as a module since modules are so often used as namespaces (e.g. `MyGemModule::SomeClass`).

I agree it's not ideal, but when RSpec is working with limited information (as it is in this case) it's not clear what the "right" thing is.

> I think in that case the Module or Class should be loaded

RSpec does not do any autoloading.  My rule of thumb is: if I want something loaded, I load it by requiring it.  Just add a `require 'model'` at the top of your spec file.  Of, if you are using Rails autoloading, reference the constant before the `stub_const` method gets executed -- for example, `RSpec.describe Model` should do the trick.

There was talk at some point about potentially adding some autoloading for this kind of situation in rspec-rails since that's a rails context where autoloading is common, but I don't remember what conclusion we arrived at and I can't find the issue.  @JonRowe do you remember?

**Comment by JonRowe** [comment]
We talked about it but never did anything about it, my suggested work around at the time was to do `stub_const("#{Model}::CONST", 2)` to trigger the autoloading.

**Comment by tdeo** [comment]
That's exactly the workaround I used as well

**Comment by keogh** [comment]
thanks for the workaround, more than 3 years after @JonRowe post, it still works! 🤔
