### ISSUE TITLE
Stubbing serialized attributes on instance_double raises error

### ISSUE THREAD

**Issue by stestaub** [rspec/rspec-mocks#1089]
I encountered the following issue.

Having ActiveRecord Model with a serialized attribute:

```ruby
class DemoProject < ApplicationRecord
  serialize :settings, Hash
end
```

Now if we would like to stub DemoProject#settings on an instance_double it will fail with `DemoProject does not implement: settings`

```ruby
describe 'instance double with method stub' do

    it 'should work with constructor arguments' do
      expect {
        instance_double(DemoProject, settings: {my_settings: 10})
      }.not_to raise_error
      # Fails with => expected no Exception, got #<RSpec::Mocks::MockExpectationError: DemoProject does not implement: settings>
    end

    it 'should work with receive(:settings)' do
      project_mock = instance_double('DemoProject')
      expect {
        allow(project_mock).to receive(:settings).and_return(my_settings: 10)
      }.not_to raise_error
      # Fails with => expected no Exception, got #<RSpec::Mocks::MockExpectationError: DemoProject does not implement: settings>
    end

  end

  describe 'stub method on intance' do
    it 'should not raise error when stubbing a method' do
      expect {
        allow(subject).to receive(:settings).and_return(my_settings: 10)
      }.not_to raise_error
      # this works!
    end
  end
```

I'm not sure how rspec-mock checks if the method exists but `#respond_to?(:settings)` returns true in this case.

The used version of rspec-mocks is 3.1.3

**Comment by myronmarston** [comment]
First off, please upgrade to RSpec 3.4.  We've fixed many bugs and added many improvements :).

Anyhow, we do not have an instance of the class to check `respond_to?(:settings)` on.  Instead, we can only check `DemoProject.method_defined?(:settings)`.  It appears that rails wrongly reports that `:settings` is not a defined method in this case.  In general, dynamic classes do not always play well with verifying doubles (as [we've documented](https://relishapp.com/rspec/rspec-mocks/v/3-4/docs/verifying-doubles/dynamic-classes)) and rails often does extremely dynamic stuff.

If it's cheap to instantiate a `DemoProject`, you can use `object_double` instead of `instance_double`:

``` ruby
object_double(DemoProject.new, settings: {my_settings: 10})
```

Whereas `instance_double` stands in as an instance of the passed argument (the class) and therefore can only interrogate the class to find out if the method is defined, `object_double` stands in for a particular object and has an object to work off of (`DemoProject.new`, in this case), so it can check `respond_to?` and it should work since you said `respond_to?(:settings)` returns true.

**Comment by stestaub** [comment]
This makes sense, thank you for the clarification and for the hint to the documentation. Rails indeed seems not to report `method_defined?(:true)` correctly.

**Comment by myronmarston** [comment]
> Rails indeed seems not to report `method_defined?(:true)` correctly.

That seems like a bug in rails I'd encourage you to report upstream.
