### ISSUE TITLE
Setting expectation on `::new` sometimes causes it to return nil

### ISSUE THREAD

**Issue by smackesey** [rspec/rspec-mocks#1092]
I have a class with this initialize method:

``` ruby
def initialize(str, **kwargs)
  @raw = str
  kwargs.each { |k,v| instance_variable_set("@#{k}", v) }
end
```

When I have an expectation set on the Class to receive `::new`, sometimes it returns nil instead of a new instance. I discovered in a class buried deep in my application and was unable to replicate it in a simpler script context. But here are some details:

The bug requires not only that I pass '*' as first arg, but also that double-splatted keyword args have certain properties:

``` ruby
kwargs1 = { :x => 1 }
kwargs2 = {:x => [/^\S*/]}
kwargs3 = {:value => [/^\S*/]}
kwargs4 = {:values => [/^\S*/]}
MyClass.new('*', **kwargs1)  # => OK
MyClass.new('*', **kwargs2)  # => OK
MyClass.new('*', **kwargs3 # => OK
MyClass.new('*', **kwargs4)  # => RETURNS nil
MyClass.new('**', **kwargs4)  # => OK
```

**Comment by myronmarston** [comment]
> When I have an expectation set on the Class to receive `::new`, sometimes it returns nil instead of a new instance.

What does your message expectation look like?  I ask because the default return value is `nil` ([as documented](https://relishapp.com/rspec/rspec-mocks/v/3-4/docs/configuring-responses)) so that's the normal behavior.  The only way to expect `new` on a class and have it return an instance is to do something like:

``` ruby
instance = MyClass.new(...)
expect(MyClass).to receive(:new).and_return(instance)
```

...or:

``` ruby
expect(MyClass).to receive(:new).and_call_original
```

Anyhow, if a simple `expect(MyClass).to receive(:new)` call is resulting in different return values based on the arguments, that's definitely a bug and something we should look into.  Can you provide a reproducible example?

On a side note, expecting a class to receive `new` is, IMO, a code smell. Generally speaking, we recommend you limit message expectations to situations where the result of the message is a side effect.  Using a message expectation to show that your subject triggers a side effect on a collaborator via a particular message makes a lot of sense.  But if the message does not trigger a side effect, expecting `new` to be received is just coupling your test to the implementation of the subject and isn't specifying anything useful about the observable behavior of the subject.

**Comment by mikegee** [comment]
@smackesey does this issue need to remain open?

**Comment by smackesey** [comment]
I no longer remember where this was cropping up and I can't replicate it, so I would say no it should not remain open.
