### ISSUE TITLE
Extending instances of RSpec::Mocks::Double

### ISSUE THREAD

**Issue by Deradon** [rspec/rspec-mocks#1100]
## Problem

> RSpec doubles can not be changed by extending its instances.

I report this problem because I run into this problem a few month ago and just today my coworker was experiencing the same problem.

## Minimum Example

```ruby
module Bar
  def foo
    "bar"
  end
end

double = RSpec::Mocks::Double.new("Foo", foo: "foo")
obj = Object.new

double.extend(Bar)
obj.extend(Bar)

double.foo
# => "foo"     # ! this should return "bar"

obj.foo
# => "bar"
```

## Complex Example

The spec I'd like to write:

```ruby
require 'spec_helper'

RSpec.describe Modifier do
  subject(:modifier) { described_class.new(active) }

  describe "#apply_to(obj)" do
    subject(:obj) { instance_double(Foo, foo: "foo") }

    before { modifier.apply_to(obj) }

    context "when active" do
      let(:active) { true }
      its(:foo) { is_expected.to eq("extended-foo") }  # NOTE: This one will fail
    end

    context "when not active" do
      let(:active) { false }
      its(:foo) { is_expected.to eq("foo") }
    end
  end
end
```

And the related implementation:

```ruby
class Modifier
  def initialize(active)
    @active = active
  end

  # NOTE: This is the interesting method
  def apply_to(obj)
    return unless active?

    obj.extend(Extended)     # NOTE: And this is the interesting LOC
  end

  def active?
    @active
  end

  private

  attr_reader :active

  module Extended
    def foo
      "extended-#{super}"
    end
  end
end

class Foo
  attr_reader :foo

  def initialize(foo)
    @foo = foo
  end
end
```

## Links

* Stackoverflow: [Test obj.extend(Foo) with RSpec doubles](http://stackoverflow.com/questions/33997298/test-obj-extendfoo-with-rspec-doubles)
* GitHub: [Repo to reproduce](https://github.com/Deradon/extend-rspec-doubles-example)

**Comment by myronmarston** [comment]
Things are working correctly.  Note that this works:

``` ruby
module Bar
  def foo
    "bar"
  end
end

double = RSpec::Mocks::Double.new("Foo")
double.extend(Bar)
double.foo # => "bar"
```

The difference between your example and this one is that you declared your double as:

``` ruby
double = RSpec::Mocks::Double.new("Foo", foo: "foo")
```

The `foo: "foo"` bit defines a singleton method on the double, so that when `foo` is received, it returns `"foo"`.  When an object has a singleton method defined on it, the singleton method definition takes precedence over the method defined in any module extensions.  For example, you can see the exact same issue with a bare object if you define a `foo` method on it:

``` ruby
obj = Object.new
def obj.foo; "foo"; end
obj.extend(Bar)
obj.foo # => "foo"
```

If you want a method from an extended module to work on a double, you'll need to avoid defining it as a stub on the double.  That's just how ruby singleton methods and module extensions interact, and there's no other reasonable way for RSpec to define method stubs on a test double outside of singleton methods.

Alternately, if this restriction of rspec's test doubles means they don't meet your needs here, you can consider writing a one-off fake as a bare ruby class that you can use here.

**Comment by myronmarston** [comment]
BTW, if you care about the performance of the code, I'd urge you to consider redesigning it to not `extend` an object at runtime, since that bust's ruby's method cache.  See https://tonyarcieri.com/dci-in-ruby-is-completely-broken for a discussion of the kind of perf hit that this causes -- and note that it's not just this object that becomes slow, but _every object in your system_, due to the global nature of Ruby's method cache.

**Comment by Deradon** [comment]
> When an object has a singleton method defined on it, the singleton method definition takes precedence over the method defined in any module extensions.

Thanks! Your example demonstrates it very well that it is working as expected.
