### ISSUE TITLE
Rails Descendant Tracking

### ISSUE THREAD

**Issue by DanielRuskin1** [rspec/rspec-mocks#1112]
I'm using rspec/rspec-mocks with a Rails application.  I recently noticed a bug with Rails descendants tracking.

Let's say we have this class structure:
```
module Cars
  class Car
    def foo
    end
  end
end
```

```
module Cars
  class Sedan < Car
  end
end
```

```
module Cars
  class Subaru < Sedan
  end
end
```

When running `descendants` on `Cars::Car`, this is returned (as expected):
```
[Cars::Sedan, Cars::Subaru]
```

After running `expect(Cars::Sedan.new).to receive(:foo)`, this is returned (with an extra class):
```
[#<Class:#<Cars::Sedan:0x007fdbb2c1ec20>>, Cars::Sedan, Cars::Subaru]
```

Any ideas on what could be going wrong here?

**Comment by JonRowe** [comment]
I'm pretty certain thats just the meta class...

**Comment by DanielRuskin1** [comment]
Thanks for taking a look. 

I'm pretty sure it is a metaclass, but why is it showing up in the descendants?  I wouldn't expect setting a rspec mock to alter descendant tracking.

**Comment by myronmarston** [comment]
> I'm pretty sure it is a metaclass, but why is it showing up in the descendants?

No idea.  I know very little about rails and have never used that part.  RSpec::Mocks certainly doesn't monkey patch any methods defined by rails (or any methods at all if you enable zero-monkey-patching mode) so it appears that rails `descendants` method includes singleton classes.  You'd have to check with the rails people to see if its intentional or not.

Regardless, to do what you've asked it to do, rspec-mocks has to do things like modify the singleton class.  If rails chooses to implement things so that it includes the singleton class there's nothing we can do about that.

**Comment by DanielRuskin1** [comment]
Makes sense, I'll close.

Thanks guys.

**Comment by flugsio** [comment]
For anyone else wondering, https://github.com/rails/rails/issues/27238
I got this issue in an old rails 4.1 project when upgraded to rails 2.3, using this as a temporary workaround `
descendants.reject(&:singleton_class?)`
