### ISSUE TITLE
expect().to raise_error should... raise an error 

### ISSUE THREAD

**Issue by olivierlacan** [rspec/rspec-mocks#1116]
For some reason I tried to assert the following:

```ruby
expect(described_class.create!).to raise_error
```

The output was:

```
Failure/Error: expect(described_class.create!(tag: tag)).to raise_error
     ActiveRecord::RecordInvalid:
       Validation failed: Needs at least one content model association.
```

Which is the error I expected would be raised. For a moment this confused me until I remembered that I need to pass a block to expect in order to make exception expectations. But I'm still surprised that raise_error didn't complain about not being given a block.

Is that a strange... expectation on my part? 😄 

PS: rspec-mocks (3.3.2)

**Comment by myronmarston** [comment]
I would _love_ to fix this but haven't been able to think up a feasible way to do so.  The problem is that ruby evaluates the argument to `expect` first (before even instantiating the `raise_error` matcher) and the expression it evaluates is raising an error.  That causes the example to fail immediately, before the `raise_error` matcher has a chance to do anything about this.

Can you think of a way we can solve this?

**Comment by olivierlacan** [comment]
Oh, yeah. Tricky. I can't think of a way that wouldn't pollute in a monkey-patchey way. Sadly can't use Refinements on `Kernel#raise` since `Kernel` a module.

Feels like you could have a monkey-patch check on `Kernel#raise` but even then it would happen before the `raise_error` expectation is registered. 

I guess there's no solution. 😢
