### ISSUE TITLE
instance_of matcher is not matching:

### ISSUE THREAD

**Issue by jcoyne** [rspec/rspec-mocks#1177]
```
  1) Blacklight::ShowPresenter#html_title with an html_title_field passes the no_html option to the FieldPresenter
     Failure/Error: FieldPresenter.new(view_context, document, field_config, options).render

       #<Blacklight::FieldPresenter (class)> received :new with unexpected arguments
         expected: (#<Double (anonymous)>, #<SolrDocument:0x007ffa0239af18 @_source={"id"=>1, "link_to_facet_true"=>"x", "link_to_facet_named"=>...8915446827338632>}, :dc_xml=>{:content_type=>"text/xml"}, :oai_dc_xml=>{:content_type=>"text/xml"}}>, an_instance_of(Blacklight::Configuration::NullField), {:no_html=>true})
              got: (#<Double (anonymous)>, #<SolrDocument:0x007ffa0239af18 @_source={"id"=>1, "link_to_facet_true"=>"x", "link_to_facet_named"=>...8915446827338632>}, :dc_xml=>{:content_type=>"text/xml"}, :oai_dc_xml=>{:content_type=>"text/xml"}}>, #<Blacklight::Configuration::NullField field="id">, {:no_html=>true})
       Diff:
       @@ -1,5 +1,5 @@
        [#<Double (anonymous)>,
         #<SolrDocument:0x007ffa0239af18 @_source={"id"=>1, "link_to_facet_true"=>"x", "link_to_facet_named"=>"x", "qwer"=>"document qwer value", "mnbv"=>"document mnbv value"}, @response=nil, @export_formats={:xml=>{:content_type=>#<Mime::Type:0x007ff9fbb0b678 @synonyms=["text/xml", "application/x-xml"], @symbol=:xml, @string="application/xml", @hash=-788915446827338632>}, :dc_xml=>{:content_type=>"text/xml"}, :oai_dc_xml=>{:content_type=>"text/xml"}}>,
       - "an_instance_of(Blacklight::Configuration::NullField)",
       + #<Blacklight::Configuration::NullField field="id">,
         {:no_html=>true}]
```

**Comment by myronmarston** [comment]
I think the output you are seeing is deceiving.  The diff is a simple textual diff (using [diff-lcs](https://github.com/halostatue/diff-lcs)), and `an_instance_of(Blacklight::Configuration::NullField)` is textually different from `#<Blacklight::Configuration::NullField field="id">`, so the differ is highlighting it as a difference, but it does not mean that it's the part that failed to match.

Try changing to `expect(Blacklight::FieldPresenter).to receive(:new).with(anything, anything, an_instance_of(Blacklight::Configuration::NullField))` -- I'd expect that to work, and show that `an_instance_of` is working just fine.

My guess is that the expected vs actual double for the 1st argument is different.  Since they are unnamed, they don't print any different, and the differ doesn't know to highlight them.  Can you try naming your doubles in this example to see if that reveals the doubles as the difference?

**Comment by jcoyne** [comment]
@myronmarston you are right, using the `anything` matchers for the first two arguments allowed the expectation to pass... So the question remains, why does the output show a diff on the third argument?

**Comment by myronmarston** [comment]
> So the question remains, why does the output show a diff on the third argument?

Because the differ we use performs only textual diffs, and `an_instance_of(Blacklight::Configuration::NullField)` is textually quite different from `#<Blacklight::Configuration::NullField field="id">`.  Our differ knows nothing about the semantics of matching.  It's as if we saved the actual arguments line-by-line to a file, saved the expected arguments line-by-line to a file, and used `git diff` to see the diff.

It's a known issue with our differ, but solving it is quite difficult (as we'd have to re-implement the differ from scratch to be aware of RSpec concepts like matching).

**Comment by jcoyne** [comment]
@myronmarston I see, thanks for taking the time to walk me through it. Close?

**Comment by myronmarston** [comment]
Sure.
