### ISSUE TITLE
How to compose hash_including and hash_not_including

### ISSUE THREAD

**Issue by kennethinsnow** [rspec/rspec-mocks#1178]
I could do sth like
```
describe 'user' do
  let(:user) { {id: 1, name: 'Foo', thread: {id: 1, title: 'Bar'}} }

  it do
    expect(user).to include(
      id: 1,
      thread: hash_including(id: 1),
      thread: hash_not_including(name:a),
    )
  end
end
```

but rubocop complains about thread being used twice, so i tried:

```
    expect(user).to include(
      id: 1,
      thread: hash_including(id: 1).and hash_not_including(name:a),
    )
```

then rspec complains about the syntax.

Anybody knows how i can compose these two matchers?

**Comment by myronmarston** [comment]
> then rspec complains about the syntax.

What syntax complaint are you seeing?

**Comment by myronmarston** [comment]
Also, in your `name:a` expression, what is `a`? It looks like a local variable or a method call, but I don't see `a` defined in your example snippet.

**Comment by kennethinsnow** [comment]
Sorry, i was trying to be concise. name: "chris"

**Comment by kennethinsnow** [comment]
This is exactly what i have:
This works
    ```
    describe 'user' do
      let(:user) { {id: 1, name: 'Foo', thread: {id: 1, title: 'Bar'}} }

      it do
        expect(user).to include(
          id: 1,
          thread: hash_including(id: 1),
          thread: hash_not_including(:name)
        )
      end
    end
```

but this one doesn't:

```
    describe 'user' do
      let(:user) { {id: 1, name: 'Foo', thread: {id: 1, title: 'Bar'}} }

      it do
        expect(user).to include(
          id: 1,
          thread: hash_including(id: 1).and hash_not_including(:name)
        )
      end
    end
```
Errors:
somefile:736: syntax error, unexpected tIDENTIFIER, expecting ')' (SyntaxError)
          thread: hash_including(id: 1).and hash_not_including(:name)
somefile:737: syntax error, unexpected ')', expecting keyword_end
somefile:742: syntax error, unexpected keyword_do_block, expecting keyword_end
somefile:889: syntax error, unexpected keyword_do_block, expecting keyword_end
somefile:890: syntax error, unexpected keyword_do_block, expecting keyword_end
        3.times do |order|
                  ^
somefile:919: syntax error, unexpected keyword_do_block, expecting keyword_end
somefile:958: syntax error, unexpected keyword_end, expecting end-of-input

**Comment by myronmarston** [comment]
> but rubocop complains about thread being used twice, so i tried:

It's not just rubocop that's complaining; while that appears to work, it actually does not.  You're passing a hash with two entries for the `:thread` key.  Ruby, for some reason, does not give you an error or warning in this case, but instead makes the 2nd entry stop the first.  So the `thread: hash_including(id: 1)` entry is completely ignored.  If you change it to `thread: hash_including(id: 2)` you'll notice the expectation still passes.

> then rspec complains about the syntax.

The syntax complaint is coming from ruby, not RSpec. Ruby just can't parse that.  You need to use some extra parens to (on the `and` method call) to allow ruby to parse it.

That said, parens alone do not fix it, because the matchers you are using (`hash_including` and `hash_not_including`) come from rspec-mocks and are not full rspec-expectations matchers, unfortunately.  We have an open issue to address this (#513) but that's the way it is for now.

Here's how I'd  do this:

``` ruby
RSpec::Matchers.define_negated_matcher :excluding, :include

RSpec.describe 'user' do
  let(:user) { {id: 1, name: 'Foo', thread: {id: 1, title: 'Bar'}} }

  it "works" do
    expect(user).to include(
      id: 1,
      thread: a_hash_including(id: 2).and(excluding(:name)),
    )
  end
end
```

Notice:

- I'm using `a_hash_including`, which is an [alias defined by rspec-expectations](http://rspec.info/documentation/3.5/rspec-expectations/RSpec/Matchers.html#include-instance_method) for `include` and therefore is a full matcher that supports the `and` method.
- I've defined a negated form of `include` as `excluding`, so that I can pass that to `and` and also so that I get an expression that reads nicely: "a hash including ... and excluding ...".

**Comment by kennethinsnow** [comment]
Thanks, that seems to work. Is there a way to not defining the negated?

**Comment by myronmarston** [comment]
> Is there a way to not defining the negated?

I don't understand what you're asking.

**Comment by kennethinsnow** [comment]
I prefer not to do if possible
RSpec::Matchers.define_negated_matcher :excluding, :include

**Comment by myronmarston** [comment]
Nope.

**Comment by myronmarston** [comment]
(At least not that I know of).

**Comment by kennethinsnow** [comment]
Ok, Thanks a lot anyway
