### ISSUE TITLE
Add `expect_multiple_instance_of`

### ISSUE THREAD

**Issue by DannyBen** [rspec/rspec-mocks#1187]
Not sure if this was discussed in other places, or if there is a trivial solution to this use case, but in several of my past projects, I encountered an issue where `expect_any_instance_of` surprised me by the fact that it raised an error when the expectation was met on multiple instances instead of just the one.

[It is my understanding][1] that `expect_any_instance_of` will only operate on a single instance, and in case several instances receive the message, it will be considered an error (in the form of: `The message 'X' was received by #<Instance:1> but has already been received by #<Instance:2>`)

I would like to propose a similar `expect` method, like `expect_multiple_instance_of` or something like that.

I know I can work around it with `allow_any_instance_of` but it is doing just part of the job for me, since I understand it will also succeed if no messages are actually received.

A sample use case, for clarification:

```ruby
require 'rspec'

# Code
class Message
  def deliver
    puts "--> Delivering message"
  end
end

class Notifier
  def deliver_all
    messages.each &:deliver
  end

  def messages
    [Message.new, Message.new]
  end
end

# Specs
describe Notifier do
  describe "#deliver_all" do
    it "delivers all messages" do
      ## Proposing this
      # expect_multiple_instance_of(Message).to receive(:deliver)
      
      ## Since this does not work
      expect_any_instance_of(Message).to receive(:deliver)
      subject.deliver_all
    end
  end
end

```

[1]: https://github.com/rspec/rspec-mocks/issues/58

**Comment by JonRowe** [comment]
`expect_any_instance_of` is considered a legacy feature (one that we do not advocate using) due to the fact that it requires significant amount of monkey patching and other such magic to work, and is ambiguous as you have just found out. As such we don't want to expand the feature set offered here. 

A better alternative here is either to test this as an integration test (not using mocks at all), pass in collaborators to the code (e.g. the mails you wish to be delivered) in which case you could use normal doubles or define regular stubs which return specific instances which you could verify the correct messages where received.

You could also naively implement this as such:

```
def expect_all_instances_of(klass)
  instance = instance_double(klass)
  expect(klass).to receive(:new) { instance }
  expect(instance)
end
```

However this won't work for all scenarios and as such we wouldn't support adding this into the main codebase.
