### ISSUE TITLE
`SystemStackError: stack level too deep` for `expect_any_instance_of(Hash).not_to receive(:[]=)`

### ISSUE THREAD

**Issue by AlexWayfer** [rspec/rspec-mocks#1200]
```ruby
require 'rspec'

RSpec.describe 'work with Hash' do
  it do
    expect_any_instance_of(Hash).not_to receive(:[])
  end
end
```

```
$ rspec rspec.rb
F

Failures:

  1) work with Hash 
     Failure/Error: expect_any_instance_of(Hash).not_to receive(:[]=)
     
     SystemStackError:
       stack level too deep
     # ./rspec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.01703 seconds (files took 0.06122 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./rspec.rb:4 # work with Hash
```

```
$ rspec -v
RSpec 3.7
  - rspec-core 3.7.1
  - rspec-expectations 3.7.0
  - rspec-mocks 3.7.0
  - rspec-support 3.7.0
```

**Comment by myronmarston** [comment]
`expect_any_instance_of` is a sharp object, and provides you with the opportunity to break RSpec itself.  RSpec uses hashes internally for many things (as you might expect) and has to use `Hash#[]` to get values out of a hash. So if you set up that expectation--which prevents `Hash#[]` from working for the rest of the example--it breaks RSpec, unsurprisingly.  I don't think there's any way we can fix this outside of avoiding the use of `Hash` within RSpec, which isn't going to happen. (Plus, it would just shuffle the problem to some other core type that a user could similarly expect not to be used).

**Comment by AlexWayfer** [comment]
> I don't think there's any way we can fix this outside of avoiding the use of Hash within RSpec, which isn't going to happen.

OK, I agree. But what about more meaningful message about it instead of inexplicable exception?

**Comment by myronmarston** [comment]
> OK, I agree. But what about more meaningful message about it instead of inexplicable exception?

That would be nice, but it's worth noting that you've stumbled upon merely one of a large number of cases like this.  If you ever use `expect_any_instance_of(SomeBuiltInType).not_to receive(:message)`, and RSpec internally uses `SomeBuiltInType#message`, you're going to break RSpec.  So there are a _very_ large number of cases that would cause similar errors.  In general, `expect_any_instance_of(...).not_to receive(...)` is only safe to use on types you own.

I don't know how to provide a meaningful message instead of this exception without special casing `Hash#[]`--but that only provides a meaningful message in one specific case instead of in the general case, which we don't want to do.  Once we start down the path of special casing certain types and methods, we may get asked to special case others because so many other cases have this problem--which again, we don't want to do.

I think the best solution for now is to improve the docs for `expect_any_instance_of` to call out that you have to use it with care on types you do not own.  Do you want to open a PR improving the docs?

**Comment by AlexWayfer** [comment]
> That would be nice, but it's worth noting that you've stumbled upon merely one of a large number of cases like this. If you ever use expect_any_instance_of(SomeBuiltInType).not_to receive(:message), and RSpec internally uses SomeBuiltInType#message, you're going to break RSpec. So there are a very large number of cases that would cause similar errors. In general, expect_any_instance_of(...).not_to receive(...) is only safe to use on types you own.
>
> I don't know how to provide a meaningful message instead of this exception without special casing Hash#[]--but that only provides a meaningful message in one specific case instead of in the general case, which we don't want to do. Once we start down the path of special casing certain types and methods, we may get asked to special case others because so many other cases have this problem--which again, we don't want to do.

OK, I agree.

> I think the best solution for now is to improve the docs for expect_any_instance_of to call out that you have to use it with care on types you do not own.

Good idea.

> Do you want to open a PR improving the docs?

English is not my native, and I'm pretty busy right now, so no :(

Thank you.
