### ISSUE TITLE
any_instance.stub still performs original method

### ISSUE THREAD

**Issue by mareczek** [rspec/rspec-mocks#1208]
In my request spec I have:
```ruby
it 'a' do
  CollectionPoint::RestartBleService.any_instance.stub(:perform)
  put restart_ble_collection_point_path(cp.id), headers: { 'Authorization': "Bearer #{@token}", 'content-type': 'application/json' }
  expect(response).to have_http_status(200)
end
```
I also tried:
```ruby
allow_any_instance_of(CollectionPoint::RestartBleService).to receive(:perform).and_return { true }
```

and the controller:
```ruby
  def restart_ble
    CollectionPoint::RestartBleService.new(@collection_point).perform
    if @collection_point.units.active.count == 0
      render json: { message: 'BLE restart failure' }, status: 480
    else
      render json: @collection_point.as_json(only: [:id, :beacon_uuid])
    end
  end
```
I want to stub `:perform` because `CollectionPoint::RestartBleService.new(@collection_point).perform` is tested in service specs. I would like to test `http_status`

```ruby
class CollectionPoint::RestartBleService

  def initialize collection_point
    @uuid   = collection_point.beacon_uuid

    # below depends on strategy
    # if a Restart BLE action should only update UUID on active units then use below
    # @units  = collection_point.units.active
    # if it should try to salvage attached units even if they are not active then use below
    @units  = collection_point.units

    @parallel_requests_count = (ENV.fetch('PARALLEL_REQUESTS_COUNT') { 4 }).to_i
  end

  def perform
    Parallel.each(@units, in_processes: @parallel_requests_count) do |unit|
      CollectionPointUnit::RestartBleService.new(unit, @uuid).perform
    end
    CollectionPointUnit.connection.reconnect!
  end
end
```
Is this possible? :)

**Comment by myronmarston** [comment]
`CollectionPoint::RestartBleService.any_instance.stub(:perform)` should work (and we have specs demonstrating it does for the cases we came up with to test it).  It's worth noting that `any_instance` and `stub` are APIs that are also provided by other mocking libraries (e.g. mocha) and it's possible if you have one of those loaded that you're using the methods provided by another library.  Can you add this to your spec to confirm you're using the rspec-mocks methods?

``` ruby
puts CollectionPoint::RestartBleService.method(:any_instance).source_location
puts CollectionPoint::RestartBleService.any_instance.method(:stub).source_location
```

Assuming those print paths containing `rspec/mocks` then there's something going on.  Any chance you have any `prepend SomeModule` going on in `CollectionPoint::RestartBleService`?  Module prepends aren't really compatible with `any_instance` (since the prepended module can intercept the call before it gets to the method stub rspec defines on the class), so that could be at fault.  If that's not what's going on, then please provide an example we can use to run locally to reproduce the problem.

You might also try using the more modern version of the syntax: `allow_any_instance_of(CollectionPoint::RestartBleService).to receive(:perform)`, although I wouldn't necessarily expect that to change anything since it uses the same underlying mechanisms.

Finally, you might consider providing a more direct `perform` class method:

``` ruby
class CollectionPoint::RestartBleService
  def self.perform(collection_point)
    new(collection_point).perform
  end

  # ...
end
```

Then you can change your controller to call `CollectionPoint::RestartBleService.perform(collection_point)` directly, and stub that method directly without involving `any_instance`.  After all, it looks like `CollectionPoint::RestartBleService` doesn't provide an object you intend to hold onto and re-use for more operations -- you just want to perform the work and through the object away.  You might as well make this usage simpler and more direct using a class method, particularly if it solves your problem.

**Comment by mareczek** [comment]
@myronmarston thank you for your time and sorry for wasting it. It was a different problem with `:focus`. `allow_any_instance_of(CollectionPoint::RestartBleService).to receive(:perform)` works as expected.

Once again sorry for wasting your time.
