### ISSUE TITLE
Mocking :new with required keyword arguments does not work

### ISSUE THREAD

**Issue by Epigene** [rspec/rspec-mocks#1209]
Not sure if I'm doing something wrong or if this is a bug, but the behavior crops up in two apps on Rubies 2.3.6 and 2.4.1, using RSpec v3.6.0 and v3.7.2 (via rspec-rails gem)

**What I am doing:**

I have a plain Ruby class with an `initialize` method that receives exclusively required keyword arguments.

```rb
class Service
  def initialize(arg:)
  end
end
```

I mock the initialization

```rb
before do
  allow(Service).to receive(:new)
end
```

**Expected outcome**

```rb
Service.new #=> nil
```

**Actual outcome**

```rb
Service.new #=> ArgumentError: Missing required keyword arguments: arg
```

From tinkering around it seems that required keyword arguments are at fault, as changing the required keyword args to optional or positional ones works:

```rb
class Service
  def initialize(arg: 1)
  end
end

before do
  allow(Service).to receive(:new)
end

Service.new #=> nil
```

**Comment by myronmarston** [comment]
This is by design.  When you configure RSpec to [verify partial doubles](https://relishapp.com/rspec/rspec-mocks/v/3-7/docs/verifying-doubles/partial-doubles) it ensures that your method stubs do not change a methods signature.  When you have this:

``` ruby
class Service
  def initialize(arg:)
  end
end
```

...then `Service.new()` will raise `ArgumentError: Missing required keyword arguments: arg` when rspec-mocks is not loaded.  Therefore, when you are using verifying partial doubles, RSpec preserves your method signature and requires the `arg` argument, just like it is normally required.

If you with to allow RSpec to change the method signature (so that no arguments are required), you can stop enabling verifying partial doubles. Although, I would recommend against that.  Using mocks and stubs to configure your objects to  be callable in ways the real object is not is a great way to have a test suite that passes all the test but doesn't actually work in practice.
