### ISSUE TITLE
Rspec unable to test #call method's receive count.

### ISSUE THREAD

**Issue by EarlofLemongrab** [rspec/rspec-mocks#1226]
### Your environment
* Ruby version: 2.3
* rspec-mocks version: 3.2

### Steps to reproduce
try to test a method is invoked with .call

it "should receive first method", :te=>true do
        a = [1,2]
        m = a.method(:first)
        expect(a).to receive(:first)
        m.call
end

### Expected behavior

expect to receive 1 time

### Actual behavior

receive only 0 time

How can I test this use case?

**Comment by myronmarston** [comment]
`m = a.method(:first)` binds `m` to the current implementation of `first`.  Later, when `m` is called, it does _not_ send the `:first` message.

`expect(a).to receive(:first)` expects that `a` receives the `:first` message.  It replaces the implementation of the `first` method with one that tracks whether or not it has received the message.  Since `m` was bound before the expectation was set, calling `m` runs the original logic and not the replaced implementation that rspec-mocks has set up.  So the spec doesn't work like how you want.

You can make it work by binding `m` to a callable that sends the `first` message:

``` ruby
  it "should receive first method", :te=>true do
    a = [1,2]
    m = -> { a.send(:first) }
    expect(a).to receive(:first)
    m.call
  end
```

...or by binding `m` to the `first` method after setting up the expectation:

``` ruby
  it "should receive first method", :te=>true do
    a = [1,2]
    expect(a).to receive(:first)
    m = a.method(:first)
    m.call
  end
```
