### ISSUE TITLE
Difference between "with()" validation of args vs. block validation of args when mixing expect+allow

### ISSUE THREAD

**Issue by lamont-granquist** [rspec/rspec-mocks#1227]
### Subject of the issue

Its a bit complicated, but what I'm really trying to do is get something that behaves a bit like a custom MessageExpectation matcher to modify the matching behavior of with().   See https://stackoverflow.com/questions/50807345/how-to-write-a-custom-messageexpectation-in-rspec/50807536#50807536 for some backstory.  The answer in that is something that I've implemented, but I'm having difficulties mixing allow+expect on the same object with the same method call, but different args, after I've converted the arg matching over to using blocks instead of `with`.

### Your environment
* Ruby version: 2.5.1
* rspec-mocks version: 3.7.0

### Steps to reproduce

```ruby
require 'spec_helper'

describe "whatever" do
  it "works" do
    obj = Object.new
    allow(obj).to receive(:shell_out!).with("foo")
    expect(obj).to receive(:shell_out!).with("bar")
    obj.shell_out!("foo")
    obj.shell_out!("bar")
  end

  it "does not work" do
    obj = Object.new
    allow(obj).to receive(:shell_out!) do |args|
      expect(args).to eql("foo")
    end
    expect(obj).to receive(:shell_out!) do |args|
      expect(args).to eql("bar")
    end
    obj.shell_out!("foo")
    obj.shell_out!("bar")
  end
end
```

### Expected behavior

I suspect there's good reasons why blocks can't be made magical like I'd want, because its not clear if the blocks "match" or not the same way that can be done to the arguments to `with()`?  If so, I guess this boils down into a request for being able to write a custom MessageExpectation.  Or maybe a request for a way to "preprocess" the actual arguments that were passed before handing off to the with() matcher?

I'm trying to get to something like:

```
describe "whatever" do
  it "works" do
    obj = Object.new
    allow(obj).to receive(:shell_out!).flatten_compact_args.with("foo", "bar")
    obj.shell_out!("foo", nil, [ "bar" ])
  end

  it "works" do
    obj = Object.new
    allow(obj).to receive(:shell_out!).flatten_compact_args.with("foo", "bar")
    expect(obj).to receive(:shell_out!).flatten_compact_args.with("baz", "quux")
    obj.shell_out!("foo", nil, [ "bar" ])
    obj.shell_out!([ "baz", nil ], "quux")
  end
end
```

**Comment by myronmarston** [comment]
When you pass a block, the block defines the new implementation of the method.  So when you do this:

``` ruby
    allow(obj).to receive(:shell_out!) do |args|
      expect(args).to eql("foo")
    end
    expect(obj).to receive(:shell_out!) do |args|
      expect(args).to eql("bar")
    end
```

...you are first replacing the existing `obj.shell_out!` implementation with `expect(args).to eql("foo")`, and then replacing that implementation with `expect(args).to eql("bar")`.  That's why it's not working how you'd like.

In general, defining a custom matcher and passing it to `with` is the normal way to go, but as you've noticed you can't write a custom matcher that is given the entire list of arguments -- each arg passed to `with` operates on a single positional arg.

The simplest way to do what you'd like is to do a single `allow` with an implementation that tracks the passed args, and then make expectations about the args at the end.  Like so:

``` ruby
  it "works" do
    flattened_arg_lists = []

    obj = Object.new
    allow(obj).to receive(:shell_out!) { |*args| flattened_arg_lists << args.flatten.compact }

    obj.shell_out!("foo", nil, [ "bar" ])
    obj.shell_out!([ "baz", nil ], "quux")

    expect(flattened_arg_lists).to include(["baz", "quux"])
  end
```

**Comment by lamont-granquist** [comment]
thanks!
