### ISSUE TITLE
Instance doubles and SimpleDelegator

### ISSUE THREAD

**Issue by AlexVPopov** [rspec/rspec-mocks#1258]
### Subject of the issue
When I try to stub an instance of a child class of `SimpleDelegator` via a verifying double I get errors of type:
> the XXX class does not implement the instance method: yyy

for methods, that the delegator is supposed to delegate to the original object.

### Steps to reproduce
I've provided an example:
https://github.com/AlexVPopov/instance_double_simple_delegator

Given the classes [`Dog`](https://github.com/AlexVPopov/instance_double_simple_delegator/blob/master/dog.rb) and [`Lab`](https://github.com/AlexVPopov/instance_double_simple_delegator/blob/master/lab.rb) the following [test](https://github.com/AlexVPopov/instance_double_simple_delegator/blob/master/spec/lab_spec.rb) fails:
```ruby
  context 'when stubbed' do
    let(:stubbed_lab) { instance_double(Lab, bark: 'Meow', color: 'gold') }

    it 'barks correctly' do
      expect(stubbed_lab.bark).to eq 'Meow'
    end
  end
```
with:

```bash
  1) Lab when stubbed barks correctly
     Failure/Error: let(:stubbed_lab) { instance_double(Lab, bark: 'Meow', color: 'gold') }
       the Lab class does not implement the instance method: bark
     # ./spec/lab_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/lab_spec.rb:22:in `block (3 levels) in <top (required)>'
```

### Expected behavior
The above test should pass

### Actual behavior
It doesn't.

I suppose, this is by design, but could you tell me what the alternatives are?

**Comment by JonRowe** [comment]
This is by design, as `Lab` does not implement `bark` or `color`, an instance of `Lab` might, but there is no way for RSpec to know this with the information provided.

Solutions!
1) Pass `Lab.new(Dog.new)`
2) Define a delegator that works at class level
3) Implement `respond_to` in your delegator which assumes it will always be used with Dog, you'd probably want to error if it was given something that wasn't dog...
