### ISSUE TITLE
Undefined method `constant_mutator_for' in around blocks.

### ISSUE THREAD

**Issue by bkuhlmann** [rspec/rspec-mocks#1283]
### Unable use mocks in around blocks

You can't seem to use mocks in around blocks which seems odd.

### Your environment

- Ruby 2.6.3
- RSpec Mocks 3.8.1

### Steps to reproduce

You can use the following example spec to reproduce:

``` ruby
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "Class Spy Example" do
  let(:object) { class_spy String }

  around do |example|
    object.inspect
    example.run
  end

  it "triggers around block" do
    puts "Test"
  end
end
```

You can also download and run this *example* gem project.

[example.zip](https://github.com/rspec/rspec-mocks/files/3419781/example.zip)

Usage:

0. `unzip example.zip`
0. `cd example`
0. `bundle install && bundle exec rake`

### Expected behavior

Would expect to see no errors.

### Actual behavior

End up with the following error:

``` bash
1) Class Spy Example triggers around block
   Failure/Error: let(:object) { class_spy String }
     The use of doubles or partial doubles from rspec-mocks outside of
     the per-test lifecycle is not supported.
   # ./spec/example_spec.rb:6:in `block (2 levels) in <top (required)>'
   # ./spec/example_spec.rb:9:in `block (2 levels) in <top (required)>'
```

This happens with the following types of mocks:

- `class_spy`
- `instance_spy`
- `object_spy`
- `class_double`
- `instance_double`
- `object_double`

**Comment by xaviershay** [comment]
Thank you for such a clear issue!

This is deliberate - you can tell from the specific error message ("not supported") rather than a random error. My memory is foggy, so I can't remember the exact reasons why not - spelunking around comments + git messages + issues would dig it up - but I seem to recall it was something about managing the state in a sane and consistent way.

Given that this fails in an informative way (tells you "not supported"), and without a proposal to fix, I'm going to close this.

Please do re-open if you unearth more context that leads you to believe this is misguided and that there is a path to a solution.

**Comment by JonRowe** [comment]
:wave: It's so they get cleaned up correctly when the example is run. As `around` doesn't guarantee an example is run it's not considered within the scope of an example. You can use them in `before(:example)` and `after(:example)`. 

You can also declare a scope for them to be used in with `RSpec::Mocks.with_temporary_scope { }.`, see: https://relishapp.com/rspec/rspec-mocks/v/3-8/docs/basics/scope

**Comment by xaviershay** [comment]
much better answer, thanks Jon :) I'd completely forgotten about `with_temporary_scope`!

**Comment by bkuhlmann** [comment]
:bow: @xaviershay and @JonRowe, excellent feedback and I learned something new. :wink:
