### ISSUE TITLE
RFC - Add warning to stubbing core libraries

### ISSUE THREAD

**Issue by JonRowe** [rspec/rspec-mocks#1341]
Applying expectations / allowances to core libraries cause us as a library issues, for example: rspec/rspec-support#428, we could maintain a list of core library modules / methods, although I think I'd probably favour just modules, which when attempted to be stubbed out in a generic way, RSpec will warn (and eventually error), that instead you probably want to apply a specific expectation.

e.g. when seeing this:

```
allow(File).to receive(:read)
```

We would warn in 3.x, but in 4.x we would error saying this behaviour is unsupported please use this:

```
allow(File).to receive(:read).with(specifc_matcher)
```

And the we would automatically default to `and_call_original` for the unstubbed method / argument combinations.

Thoughts @rspec/rspec ?

**Comment by pirj** [comment]
We would have to go case by case, as some of the stubbed methods don't accept methods (`Dir.getwd`).
Also, it will be possible to bypass our checks by passing `anything` or `any_args`.
We'll have to also check if `and_call_original` is called or not.
Might also need to check if it's an expectation or an allowance.
Also, constants, e.g. `File::SEPARATOR`.

With all that it's getting way too complicated. I'd go with static linting.

**Comment by myronmarston** [comment]
While I'm not really involved in RSpec these days, I was pinged about this via Jon's `@rspec/rspec` above and thought this was interesting, so here's my two cents :).

* I think warning or erroring on core libraries would be hard to implement in a way that's consistent and that doesn't confuse users.  Jon mentions maintaining a list somewhere but RSpec users would have a hard time understanding what's in the list and what's not in the list (and honestly, they shouldn't be expected to understand such a list...).
* Automatically stubbing `and_call_original` for certain cases (and not others) is incredibly confusing and inconsistent.
* Adding `.with(specific_matcher)` doesn't truly solve the problem, IMO: the matcher might be too broad, and even with the matcher it might still interfere with RSepc.  For example, `.with(anything)` would be a specific matcher but would still be a problem.  Or even something like `with(a_string_including("user"))` could be a problem: maybe the file RSpec's trying to load is `user_spec.rb`.
* We've dealt with this before: a long time ago, when users would stub `Time` (e.g. manually or with `Timecop` or whatever...) it interferred with RSpec's ability to accurately print how long a spec took.  Our solution was to [Make a copy of `Time.now`](https://github.com/rspec/rspec-core/blob/v3.9.2/lib/rspec/core.rb#L144-L152) that RSpec uses internally, so that if/when users stub `Time.now`, RSpec is not affected.  A similar thing can be done with `File.read`.
* If y'all want to pre-emptively do that for other core library methods used by RSpec, feel free, but it doesn't seem like this is really a widespread problem (RSpec's had half a billion downloads, and we've had the time issue a long time ago and now a `File.read` issue that's been reported by one user...). IMO it's OK to just react to these as users report them, and make copies of the core methods used by RSpec.

**Comment by benoittgt** [comment]
Hello 

I enjoyed the discussion on https://github.com/rspec/rspec-support/issues/428. It seems a complicated task to handle lot's of cases properly. I found this is a good idea to handle the most relevant scenario in RSpec like it was handle for `Time.now`. The code is clear and I don't expect we see many more errors.

**Comment by JonRowe** [comment]
Thanks for the input team, and thanks for the reminder of how we'd solved this in past @myronmarston! I think thats a better plan, so I've opened rspec/rspec-support#431 for that specific issue.
