### ISSUE TITLE
Suppress warnings for #initialize if sending to original.

### ISSUE THREAD

**Issue by envygeeks** [rspec/rspec-mocks#337]
I was wondering if there were any side affects that were mitigated by doing `#and_call_original` and if there are then can the warning messages could be suppressed if we do something like:

``` ruby
Object.any_instance.should_receive(:initialize).
  .with(kind_of(String), kind_of(Hash)).and_call_original
```

**Comment by JonRowe** [comment]
@krtschmr mock `<Class>.new` instead

**Comment by krtschmr** [comment]
@JonRowe 

so we had this, which threw the warning. it's happening deep down inside a service class which creates some other stuff. 

```
# this will trigger an exception (which we ignore)
allow_any_instance_of(ContractHtml).to receive(:initialize).and_return(nil)
```

your solution didn't worked for me. since it's rails and we have strong validations that `html` must be present, i changed it to

`allow_any_instance_of(ContractHtml).to receive(:html).and_return(nil)`

(so that triggers and validation error, thus my spec can handle the exception). works fine. thanks! 💪🏿

**Comment by krtschmr** [comment]
@pirj 

you tell me please. i am happy to learn about it more. 

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/13366714/205769257-127035b1-5993-4ff4-b284-6342c0d580b6.png">

**Comment by krtschmr** [comment]
to give more context and maybe i can learn something


when a contract moved through the signing phase, some `ContractHtml` will be generated. once generated, it actually moves forward (workflow step). to simulate what would happen, if an error during the ContractHtml generation happens, this test somewhat mimicked an "error". 

```
    it "won't move to the signing_phase if an error happened during the generation of contract_html" do
      # this will trigger an exception (which we ignore)
      allow_any_instance_of(ContractHtml).to receive(:html).and_return(nil)

      expect do
        move_to_state!(2)
      rescue StandardError
        nil
      end.to not_change { contract.reload.template_workflow_step_id }

      expect(contract.contract_html).to be nil
    end
  end
```


the actual implementation of the generation

```
 class ContractHtmlCreation
      ....
    def call
      I18n.with_locale(@contract.template.language) do
        ..... 
        html = page.to_html
        @contract_html = ContractHtml.create!(contract: @contract, html: html)
      end
      raise "no contract_html was created" unless @contract.reload.contract_html.persisted?
    end
  end
end
```

while the ContractHtml then is just Active Record 

```
class ContractHtml < ApplicationRecord
  belongs_to :contract, class_name: "Document", required: true
  validates :html, presence: true
```

i just saw this warning and wanted to do something about it, so i just said "html" will always be nil, which then will throw an activemodel error, thus no ContractHtml generated, spec is ✅ 

can you please help me, based on your experience, what could be "wrong"  with this approach and how you might have solved it?

**Comment by JonRowe** [comment]
@pirj it doesn't matter what`initialize` returns, `new` is essentially `allocate.tap { |instance| instance.initialize }`

**Comment by pirj** [comment]
Tell me what changes `template_workflow_step_id`. You expect it not to change.
Where `page` comes from it the example?
Why do you stub it at all?
Why do you `rescue`?
How would `contract_html.persisted?` be `false` after calling a bang-`create!` on it?

So far, I only have more questions about this code.

> i can learn something

I suggest you to use our [help channels](https://rspec.info/help/) for learning. We reserve issue tracker for bugs/features.

If you can provide an easily reproducible minimal example of this warning for some straightforward code example, please feel to do so.

**Comment by krtschmr** [comment]
@pirj the `template_workflow_step_id` would change, if contract_html is created. which i don't want to create, thus i hack an exception into.
`page` is some nokogiri stuff, after some actionview rendering it does some manipulation on it.
the rescue was needed, otherwise the test fails due to an exception. 
`contract_html.persisted?` is false as `create!` threw the exception, due to the stubbing, thus `template_workflow_step_id` hasn't changed.
