### ISSUE TITLE
object.respond_to? causing issues with rails after rspec-mocks upgrade

### ISSUE THREAD

**Issue by justin808** [rspec/rspec-mocks#756]
I'm using ruby 2.1.2 and rails 4.0.8.

Rails has an implementation of respond_to? that takes only 1 arg. Ruby 2.1.2's implementation takes 2 args apparently. The rspec-mocks call this with 2 args.

Maybe this is more of a Rails 4 issue when running with Ruby 2.1.2?

In `method_reference.rb`

``` ruby
      def self.method_visibility_for(object, method_name)
        instance_method_visibility_for(class << object; self; end, method_name).tap do |vis|
          # If the method is not defined on the class, `instance_method_visibility_for`
          # returns `nil`. However, it may be handled dynamically by `method_missing`,
          # so here we check `respond_to` (passing false to not check private methods).
          #
          # This only considers the public case, but I don't think it's possible to
          # write `method_missing` in such a way that it handles a dynamic message
          # with private or protected visibility. Ruby doesn't provide you with
          # the caller info.
          return :public if vis.nil? && object.respond_to?(method_name, false)
        end
      end
```

And I'm trying to stub a value like this:

``` ruby
        allow(Bpos::Application::config).to receive(:initial_image_max_lag_minutes).and_return(120)
```

`railtie/configuration` implements respond_to?(name):

``` ruby
      def respond_to?(name)
        super || @@options.key?(name.to_sym)
      end
```

Here's the full error

```
ArgumentError: wrong number of arguments (2 for 1)
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/railties-4.0.8/lib/rails/railtie/configuration.rb:83:in `respond_to?'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/method_reference.rb:94:in `block in method_visibility_for'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/method_reference.rb:85:in `tap'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/method_reference.rb:85:in `method_visibility_for'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/proxy.rb:294:in `visibility_for'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/method_double.rb:38:in `visibility'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/method_double.rb:48:in `configure_method'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/method_double.rb:150:in `add_stub'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/proxy.rb:112:in `add_stub'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/matchers/receive.rb:88:in `setup_method_substitute'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/matchers/receive.rb:76:in `setup_mock_proxy_method_substitute'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/matchers/receive.rb:37:in `setup_allowance'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/targets.rb:45:in `define_matcher'
/Users/justin/.rvm/gems/ruby-2.1.2@bpos/gems/rspec-mocks-3.0.3/lib/rspec/mocks/targets.rb:14:in `block in delegate_to'
./spec/models/photo_session/status_methods_spec.rb:212:in `block (4 levels) in <top (required)>'
```

**Comment by ggarnier** [comment]
I started having this same issue after updating rspec-rails from 2.99.0 to 3.1.0. I'm using Rails 4.2.0 and Ruby 2.1.2. I have this code:

    class Video
      def closed?
        self.respond_to?(:subscriber_only) and self.subscriber_only?
      end
    end

And this test:

    allow(video).to receive(:respond_to?).with(:subscriber_only).and_return(true)
    allow(video).to receive(:subscriber_only?).and_return(true)
    expect(video.closed?).to be_truthy

The error message is:

    Failure/Error: allow(video).to receive(:subscriber_only?).and_return(true)
      #<Video ...> received :respond_to? with unexpected arguments
         expected: (:subscriber_only)
              got: (:subscriber_only?, false)
        Please stub a default value first if message might be received with other args as well.

Seems like rspec-mocks is calling the object's `respond_to?` with the second optional parameter, according to https://github.com/rspec/rspec-mocks/blob/master/lib/rspec/mocks/method_reference.rb#L93

A temporary solution that works for me is:

    allow(video).to receive(:respond_to?).with(:subscriber_only).and_return(true)
    allow(video).to receive(:respond_to?).with(:subscriber_only?, false).and_return(true)
    allow(video).to receive(:subscriber_only?).and_return(true)
    expect(video.closed?).to be_truthy

**Comment by myronmarston** [comment]
`respond_to?` is one of those object protocols that rspec-mocks relies upon to work correctly, and in general, if you mess with how `respond_to?` works (which is what you are doing when you stub it!) you are going to run into trouble.  It's a method I would recommend you never stub.

In your specific case, you don't even need to stub `respond_to?`; the act of stubbing `subscriber_only?` defines (or defines, if it already exists) the `subscriber_only?` method on `video`, and because the method is defined, `video.respond_to?(:subscriber_only?)` will return `true` without you needing to stub `respond_to?`.

All that said, there are a couple code smells in the example you posted that suggest there may be better ways to do what you're trying to do.  Specifically:

* Calling `self.respond_to?` is quite odd (in ~7 years of using ruby as my primary language, I don't think I've ever seen that, except as a means to detect differences in ruby versions).  You've defined the `Video` class; in the context of that class, don't you know what methods it has?  Why should an object ask itself if it responds to a message before sending the message to itself?
* Stubbing methods on the object-under-test is a code smell as well.  It blurs the line between the test environment (e.g. the mocks and stubs being used to control the environment in which a test runs) and the object-under-test, and generally makes things harder to reason about.  Generally it's best to limit mocking and stubbing to collaborators (e.g. other objects that an object uses to fulfill its responsibilities).

As it stands, your test is tightly coupled to the implementation and isn't telling you much about how `Video` instances will behave in production since you've patched them in your test to behave a particular way.  My recommendation is to consider refactoring the implementation, and also consider testing it with a less fake/more integrated test that doesn't replace method definitions on the object-under-test.

**Comment by ggarnier** [comment]
Actually, my code is a little more complicated than that. I posted only the method being tested, but `Video` is a module that may be included into other classes, and that's why we need to check if the object responds to `subscriber_only`. But I agree with you, the test is too coupled to the implementation. I'm refactoring the test to this:

    context "when video is for subscribers only" do
      before do
        def video.subscriber_only
          true
        end
      end

      it "should return true" do
        expect(video.closed?).to be_truthy
      end
    end

**Comment by myronmarston** [comment]
>  posted only the method being tested, but Video is a module that may be included into other classes

Ah, the fact that it's a module matters.  In your example, it was `class Video`, so I assumed it was a class :).

**Comment by ggarnier** [comment]
Yes, I'm sorry, that example should be `module Video`.

**Comment by jeropaul** [comment]
I've got an old rails application (3.2.21) that I've just updated to rspec 3.0.x.

Anyway I have a few tests that stub configuration like:
`Rails.configuration.stub(:some_configuration_item => 'value')`

which unfortunately fails with a really unhelpful message because `railsties-3.2.21/lib/rails/railtie/configuration.rb` doesn't deal with the respond_to?(:method_name, include_all=false)

respond_to is defined as `respond_to?(symbol, include_all=false)`  is there a reason your passing in the default value?

**Comment by JonRowe** [comment]
Instead of stubbing one value on configuration replace it with a double? e.g.

```Ruby
allow(Rails).to receive(:configuration) { double some_configuration_item: 'value' }
```

**Comment by jeropaul** [comment]
That's an awesome quick response, yeah that works.  Thanks

**Comment by fschwahn** [comment]
Just a quick question, I googled but nothing came up except for this issue. You say one should never stub respond_to, but what is the recommended way to test eg. the following:

```ruby
if array.respond_to?(:sort_alphabetical)
  array.sort_alphabetical
else
  array.sort
end
```

Stubbing respond_to leads to stack level too deep, doing `Array.send(:undef, :sort_alphabetical)` removes the method for the entire test suite. Passing a custom object as `array` (ie. dependency injection) is also not possible with the current code. Is there any easy way to test this?

**Comment by JonRowe** [comment]
Stub whatever is returning the array, as per above.

**Comment by fschwahn** [comment]
Unfortunately that's not really an option with the current code - the array is generated in a number of private methods. For the record, what I ended up doing is this:

```ruby
before do
  Enumerable.send(:alias_method, :_sort_alphabetical, :sort_alphabetical)
  Enumerable.send(:remove_method, :sort_alphabetical)
end

after do
  Enumerable.send(:alias_method, :sort_alphabetical, :_sort_alphabetical)
end
```

**Comment by xaviershay** [comment]
> Unfortunately that's not really an option with the current code

Not particularly constructive, but mocks don't tend to work so well if you can't refactor the code as well. Mocks are primarily a design tool, if you're using them to try and make legacy code testable you're probably in for a bad time. (Usually because they are fragile, don't represent the seams of the system, and end up creating a test suite that doesn't prove much but breaks easily.)
