### ISSUE TITLE
RSpec 2.14 -> 2.99 test failure: doubles don't serialize nicely

### ISSUE THREAD

**Issue by marten** [rspec/rspec-mocks#777]
We had an ActiveRecord model with a serialized column, in which we stored a `double("Name")`. This worked fine in 2.14, but in 2.99.2 this results in the exception: `NoMethodError: undefined method`[]' for nil:NilClass`.

Presumably doubles don't deserialize the same way? I've worked around the issue in our codebase by not putting doubles in serialized columns, but since the suite was supposed to remain green, I wanted to mention this issue here. Feel free to reject it for any reason, I won't feel bad.

**Comment by ptrikutam** [comment]
@myronmarston I'm still having this issue, except it fails on this line for me:

https://github.com/rspec/rspec-mocks/blob/v2.99.4/lib/rspec/mocks/test_double.rb#L81

Any thoughts on what I can do to fix?

**Comment by ptrikutam** [comment]
I've got a fix in the commit (https://github.com/somawater/rspec-mocks/commit/bb6ec2e3afada1b571bdea38a61d2da0f44e624b) referenced above, but to be frank I don't know the implications of not assigning `@__unfrozen_attributes` if the value isn't present.

How can I test this change I've made so that I know I'm not breaking anything?

**Comment by ptrikutam** [comment]
FYI this occurs only in tests where where I'm using `.as_null_object`.

**Comment by JonRowe** [comment]
Does this occur on 3.3?

**Comment by ptrikutam** [comment]
It does not. It's only for 2.99.
