### ISSUE TITLE
Builder <hash/> with 3.2

### ISSUE THREAD

**Issue by cgriego** [rspec/rspec-mocks#892]
Using rspec-mocks 3.1, I had the following double:
```ruby
double("request detail").tap do |request_detail|
  allow(request_detail).to receive(:to_xml) { |options| options[:builder].tag!(:request) }
end
```

The `options[:builder]` was an instance of Builder::XmlMarkup and it produced `<request/>`. But with rspec-mocks 3.2 it generates `"<hash/>\n<request/>"`.

**Comment by myronmarston** [comment]
Thanks for reporting this.  The change is due to #868 which provides a fix for #865.  To detect situations when arguments have been mutated we use `Object#hash` and compare the value of that from when the message was received compared to when `have_received` is later used.  Calling `hash` on the builder adds that extra bit you see.

I have a fix in mind that I'll try to push later.

**Comment by myronmarston** [comment]
OK, so I've spent some time trying to work up a fix and it's a lot harder than I thought initially.  Currently we call `arg_list.hash` -- and the implementation of `Array#hash` calls `hash` on each item in its list.  I was thinking about switching to calling `hash` individually on the items, and putting a `Kernel === arg` check in there so we can skip the call to `hash` on things that don't include `Kernel` (which includes `Builder::XmlMarkup`, `BasicObject`, etc).  However, that wouldn't actually fix the problem for you -- in your case, the builder is nested inside a hash, so to detect that, I'd have to recursively check `Kernel === arg` on the entire data structure.  That's simple enough with arrays and hashes but starts to get hairy when you consider the arg list can contain _any_ kind of object, which could reference a `Builder::XmlMarkup` at any level.  Suddenly, we're looking at having to inspect all the instance variables of any given object, recursively, in addition to handling common data structures, and now it's getting extremely complex.

So for now the only way I can see to fix this is to revert #868.  However, that was the only way we could come up with to deal with the confusing failure from #865.

I would say that rspec-mocks relies a number of common `Object` methods to work, and objects that change the semantics of those methods (such as `Builder::XmlMarkup`) may run into problems as you have here.  That said, you're only passing the builder object as an argument, and not actually mocking or stubbing it, which is a reasonable thing to do, so I do think we need to do something about this.

@jferris -- any ideas for how we can deal with this (and #865) w/o totally reverting the solution we came up with in #868?

**Comment by jferris** [comment]
This is certainly getting exciting! The recursive structure problem is somewhat frustrating. Some thoughts that could be used as starting points:

If calling `hash` on the arguments somehow causes mutation (as in the case of `Builder::XmlMarkup`), the return value will change with each invocation. You could compute the `hash` twice when first receiving the arguments to verify that it doesn't change. This doesn't fix the problem, but at least gives you an opportunity to warn the user that something is probably going wrong.

I played around with `Builder::XmlMarkup` locally, and I'm actually surprised this is behaving the way it is. If I put an `XmlMarkup` instance in an `Array` and call `Hash`, I get an error: `TypeError: no implicit conversion of String into Integer`. I think the [error handling in `proxy.rb`](https://github.com/rspec/rspec-mocks/pull/868/files#diff-5e732c165cb40508878a32c8c6bd7ad5R178) is likely swallowing this error.

According to Ruby's documentation, `a.eql?(b)` implies that `a.hash == b.hash`. If this isn't the case, 1) the implementation of that object violates basic expectations in Ruby and 2) you can't reasonably expect RSpec to compare two instances of that object, since the implementation violates the basic semantics of equality in Ruby. Given all that, does it make sense to stop swallowing errors related to `hash` and instead make that into a failure?

**Comment by myronmarston** [comment]
> If calling hash on the arguments somehow causes mutation (as in the case of Builder::XmlMarkup), the return value will change with each invocation. You could compute the hash twice when first receiving the arguments to verify that it doesn't change. This doesn't fix the problem, but at least gives you an opportunity to warn the user that something is probably going wrong.

Interesting idea...it's unfortunate that as you noted, it wouldn't actually work in this case.  Also, it seems like we can't actually count on `#hash` returning a different on each invocation if calling it causes a mutation.  After all, causing a mutation is already violating the semantics of `#hash` so can we really count on such an object to properly return a different value from `#hash` each time it is mutated?

> According to Ruby's documentation, `a.eql?(b)` implies that `a.hash == b.hash`. If this isn't the case, 1) the implementation of that object violates basic expectations in Ruby and 2) you can't reasonably expect RSpec to compare two instances of that object, since the implementation violates the basic semantics of equality in Ruby.

Yep.  Problem is, in a case like @cgriego's, it's very non-obvious that RSpec is going to be comparing that object.  He's just stubbing the method to give it particular behavior via a block, and he hasn't told RSpec to do anything with the arguments at all.  The fact that RSpec is going to call `#hash` is an implementation detail and not something that users should generally need to be aware of.

> Given all that, does it make sense to stop swallowing errors related to hash and instead make that into a failure?

That's one possible change we could make.  Problem is, in a case like @cgriego's, the user would then get a `TypeError: no implicit conversion of String into Integer` error from deep in the bowels of RSpec, which the user would probably report back to us as a bug in RSpec since it certainly looks like one.

Ultimately, we do our best to support all manner of objects users throw at us, and when that isn't feasible I'm fine saying "your object violates core semantics of ruby objects, so we can't support you" -- but in this case the user isn't asking RSpec to mock or stub the object, or setting an expectation on it, or doing anything that would cause a user to expect RSpec to even care about the object.  So while it's reasonable for us to say "we don't support mocking or stubbing this object because it is too weird" I think it's less reasonable to say "you can't include this object in any data structure or object passed as an argument to a stubbed method".

Objects that redefine core methods like `hash` certainly make things difficult for us :(.

**Comment by cgriego** [comment]
Thank you for working on this. :+1:

**Comment by myronmarston** [comment]
@cgriego -- for now, a simple work around is to bypass rspec-mocks altogether and stub the method yourself via a simple `def`:

``` ruby
double("request detail").tap do |request_detail|
  def request_detail.to_xml(builder:, **options)
    builder.tag!(:request)
  end
end
```

The general caveat with defining stubs via your own `def` is that RSpec won't undo/"reset" the stub when the example completes.  That's extremely important when dealing with partial doubles (particularly globally accessible ones, like classes) but probably doesn't matter for an isolated pure test double like you are using here.

**Comment by jferris** [comment]
I thought about this over the weekend, and I can't come up with a workaround. Given the fact that you can't reliable traverse a deep tree to figure out if there's a problematic object somewhere in the arguments, and given the fact that you can't measure an object's `hash` without potentially changing it, it seems like there are some objects you just can't compare reliably. I think I'm out of ideas.

**Comment by myronmarston** [comment]
So it seems like it comes down to choosing between:

* Providing a good error message when the user uses `have_received` in a situation we can't support.
* Allowing non-standard objects like `Builder::XmlMarkup` instances to be passed as arguments to a mocked or stubbed method.

It seems wrong for us to restrict what arguments the users can pass, and the first choice isn't any kind of feature or new functionality, so I'm leaning towards reverting #868.

What do others think?

/cc @rspec/rspec

**Comment by xaviershay** [comment]
After reading through #865, I think I agree we should revert #868 and add a note of caution to the spies documentation (or wherever is appropriate) instead. #865 is a weirder case than the one in this issue.
