### ISSUE TITLE
expect_any_instance_of behavior does not match Relish documentation

### ISSUE THREAD

**Issue by tmertens** [rspec/rspec-mocks#910]
**summary**

If an expectation is set on a method on `any instance` of a class, rspec-mocks raises an `RSpec::Mocks::MockExpectationError` reading `The message 'bar' was received by #<Foo:1> but has already been received by #<Foo:2>` when the message is received by more than one instance of the class.  This behavior is incongruent with both the name of the method as well as the Relish documentation for `expect_any_instance_of`.

**description**

I'm in the middle of completing a conversion from mocha to rspec-mocks, and an issue I ran into is a difference between the implementations of expecting any_instance of a class to receive a message.  While I expect differences between the two mock frameworks, I found that the actual behavior of RSpec's `expect_any_instance_of` does not match the stated behavior in the Relish documentation:

https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/working-with-legacy-code/any-instance
> For example, in expect_any_instance_of(Widget).to receive(:name).twice it isn't clear whether each specific instance is expected to receive name twice, or if two receives total are expected. (It's the former.)

Note especially that the 'former' case states "**each specific instance** is expected to receive".

The documented behavior is further supported by the method name `expect_any_instance_of`, which reads like `expect_one_or_more_instances_of`.

Because `any_instance` does not permit the use of spies, we cannot verify after the fact that each instance received an allowed message, nor can we set an expectation on multiple instances of a class to receive a message due to the above error.  This makes it impossible, as far as I know, using `expect_any_instance_of` to expect a specific message to be called on more than one instance of a class.

**proposed resolution**

Either the documentation should be clarified, or the behavior updated to reflect the correct behavior.  IMO the expectation error currently being thrown here would be more appropriate to apply as a conditional expectation, or using different syntax.  e.g:

```ruby
expect_an_instance_of(Foo).to receive(:bar) # 'an' instead of 'any'
expect_any_instance_of(Foo).to receive(:bar).on(1).instance # Using some kind of expectation constraint, but this is very ugly.
```

**workaround**

For others, I am using the following workaround to circumvent this issue:

```ruby
module RSpec
  module Mocks
    module ExampleMethods
      # @param [Class] The class whose instances to stub or modify in the yielded block.
      # @param [Block] A block to yield immediately after the constructor is called.
      def with_all_instances_of(klass)
        raise 'Expected a block to be supplied!' unless block_given?
        allow(klass).to(
            receive(:new).and_wrap_original do |m, *args|
              instance = m.call(*args)
              yield instance
              instance
            end)
      end
    end
  end
end
```

Usage (including a failing example demonstrating the above implementation works):

```ruby
module RSpec
  module Mocks
    module ExampleMethods
      # @param [Class] The class whose instances to stub or modify in the yielded block.
      # @param [Block] A block to yield immediately after the constructor is called.
      def with_all_instances_of(klass)
        raise 'Expected a block to be supplied!' unless block_given?
        allow(klass).to(
            receive(:new).and_wrap_original do |m, *args|
              instance = m.call(*args)
              yield instance
              instance
            end)
      end
    end
  end
end

class MyTestClass
  def name
    "FooBar"
  end
end

RSpec.describe MyTestClass do
  describe 'passing examples' do
    it 'stubs every instance' do
      allow_any_instance_of(described_class).to receive(:name).and_return("BarFood")
      expect(described_class.new.name).to eql "BarFood"
      expect(described_class.new.name).to eql "BarFood"
    end

    it 'expects on every instance' do
      with_all_instances_of(described_class) do |instance|
        expect(instance).to receive(:name).and_return("BarFood")
      end
      expect(described_class.new.name).to eql "BarFood"
      expect(described_class.new.name).to eql "BarFood"
    end
  end

  describe 'failing examples' do
    it 'expect_any_instance_of fails if more than one instance fulfill the expectation' do
      expect_any_instance_of(described_class).to receive(:name).and_return("BarFood")

      expect(described_class.new.name).to eql "BarFood"
      expect(described_class.new.name).to eql "BarFood" #This will raise
    end

    it 'expectations within with_all_instances_of block fail if not met on one or more instances' do
      with_all_instances_of(described_class) do |instance|
        expect(instance).to receive(:name).and_return("BarFood")
      end
      expect(described_class.new.name).to eql "BarFood"
      described_class.new
    end
  end
end
```

**Comment by JonRowe** [comment]
`expect_any_instance_of` does (and has always in our case) referred to a single instance, so the documentation is slightly wrong on this, (see #911), we consider the use of `any_instance` to be a code smell and only be useful when working with legacy code and so we don't really want to extend the behaviour further

**Comment by Senjai** [comment]
@JonRowe While I agree that this is a codesmell, this is often the only way to test situations where instances are created dynamically. The canonical example is active record, where you can have a reference to an instance, but a query will generate a new instance that you cannot grab an instance of, and those two instances are different.The only way to get around this is:

Testing the end result of a method, which can be outside the scope of the test. E.g. verifying that something happened outside of the object under test which now creates dependencies on the test to external objects in the system.

Or

Stub out the entire query chain to provide the instances yourself, potentially missing issues with the query itself, and run expectations on those instances.

Both of these situations aren't optimal and both can occur outside of ActiveRecord. Again, agreeing that there is a code smell here, I don't see why we shouldn't support this. Am I misguided here?

**Comment by Senjai** [comment]
cc @myronmarston

**Comment by JonRowe** [comment]
You have a few tactics here which are, in my opinion, better than using any instance.

1) Stub out the query chain and return a specific double.

This is the best approach if you're attempting to test something outside of active record where you want the speed of using doubles over the reliability of an integration check. Assert on what you're passing the query and let active record do its magic in reality.

2) Don't stub this at all.

If the query is sufficiently complex to require real execution then you shouldn't be stubbing the result, write it as an integration check.

3) Both.

Refactor the query into a method on the model, or a on a service object and write an integration test checking the query, then use stub the method on a unit test for the object consuming the result of the query.

**Comment by joelpresence** [comment]
Can we reopen this?  I just got burned by this as well while testing ActiveJob subclasses.

I have two jobs, `BeginCampaignJob` and `SendCampaignPushesJob`, both of which operate independently of each other and both of which create and use their own instance of `CampaignManager`.  I want to have a test like the following:
```
it "should read the campaign" do
  expect_any_instance_of(CampaignManager).to receive(:read_campaign).twice.with(@campaign_id).and_return(success: true, data: {})
  perform_enqueued_jobs do
    # Within perform_later, read_campaign is called once but
    # an instance of SendCampaignPushesJob is also created through perform_later and it also calls read_campaign
    BeginCampaignJob.perform_later @campaign_id
  end
end
```
This fails with a message that two different instances are receiving `read_campaign`.  I don't know how else I can do this.  Each of these two jobs calls read_campaign once.  It's too complicated to stub out the complete chain.

How is it code smell that I need to use `expect_any_instance_of` in this case?  Any suggestions, @JonRowe  would be hugely appreciated!

What I really need to test here is that "read_campaign gets called twice, once each for two different instances of CampaignManager".  How would I test that?

**Comment by JonRowe** [comment]
@joelpresence As mentioned above the 'expect_any_instance_of` refers to one instance, not multiple so your use case isn't a correct use of the feature.

Personally I'd stub out `SendCampaignPushesJob` within your tests for `BeginCampaignJob` here, and then stub `new` to return a specific double within `BeginCampaignJob`.

**Comment by tmertens** [comment]
@joelpresence Why don't you just test the two jobs separately?  e.g. expect that the first creates the second job with the correct parameters, and then write a separate test for `SendCampaignPushesJob`.

It is a code smell here, as you are testing the full integration behavior of two completely separate jobs through the interface of the first.

**Comment by joelpresence** [comment]
@JonRowe I appreciate your feedback, but I respectfully disagree with your statement that "your use case isn't a correct use of the feature."  The name of the method is "expect_any_instance_of" so I would expect this to mean that any instance could receive it.  Instead, you've implemented it so that it refers to a single instance.  So really, "expect_any_instance_of" actually means "expect_exactly_one_instance_of" and the name "expect_any_instance_of" is deceptive in my opinion and a violation of the Principle of Least Surprise.

It seems like myself and a number of other users are getting burned by this.  I'm not trying to be a whiner or argumentative - I really do appreciate all the hard work you all put into rspec.  :-)  That being said, I find myself being burned by this repeatedly  and I wonder if you would consider a PR to update the behavior of this method to actually behave like "any_instance_of" or at least consider deprecating "expect_any_instance_of" and renaming it to "expect_exactly_one_instance_of"?

The problem is that I have two separate chunks of code that each create their own instance of CampaignManager, so when I want to do something like:
```
expect_any_instance_of(CampaignManager).to receive(:foo).at_least(3).times ...
```
I really just mean that foo gets invoked a total of 3 times.  I don't care which instance it's on, just that it gets invoked 3 times.  Having to stub out a `make_campaign_manager` in each chunk of code just so they can return the same campaign manager instance to make this work feels really artificial and also feels like code smell to me.  Now I'm writing actual production code in critical code areas just to help out the testing code (rspec) function as the name `expect_any_instance_of` implies to me that it should.  That feels much more artificial and smelly to me than updating `expect_any_instance_of` to actually behave like the `any_instance_of` implies and not instead of `a_single_instance_of` in its implementation.

Is it difficult to make it actually work across any instance (i.e. multiple instances)?  I get that we may have philosophical differences here and I really do mean this all with the utmost respect.  :-) But I'm feeling unheard and frustrated ... :-(

As it is currently implemented, the behavior of `expect_any_instance_of` is not really useful to me and is confusing.  Really, it's identical to `expect(@known_instance)` except it saves me the trouble of storing the single reference `@known_instance`.  But that also feels like code smell ...

Cheers!

**Comment by JonRowe** [comment]
> The name of the method is "expect_any_instance_of" so I would expect this to mean that any instance could receive it. Instead, you've implemented it so that it refers to a single instance. So really, "expect_any_instance_of" actually means "expect_exactly_one_instance_of" and the name "expect_any_instance_of" is deceptive in my opinion and a violation of the Principle of Least Surprise.

Yes which is why it's considered a test smell and a legacy feature and why we generally don't expand it.

**Comment by JonRowe** [comment]
> Is it difficult to make it actually work across any instance (i.e. multiple instances)?

It would break the existing usage, I'd rather remove the feature alltogether since we don't recommend using it.

**Comment by joshuanathanson** [comment]
I also don't get how it's code smell to want to test that some number of instances were created and they each receive a message.

Take a simple example:
`def self.foo
  (1..2).to_a.each do
    Bar.new.baz
  end
end`

**Comment by JonRowe** [comment]
Partial doubles themselves are a test smell (as it would be better to
extract the logic so that you can pass in a collaborator which is a pure
double) and because its interfering with the internals of Ruby for what is
a implementation detail. This should be integration tested (with proper
instances of Bar) if you care about the outcome.

If either of those are two complex for your actual code versus this
trivialised example then you've just proved why this is a test smell.
>
>

**Comment by joelpresence** [comment]
@JonRowe I am having issues with this again.  I am trying to "turn off" an ActiveRecord validation so that I can get a certain kind of model into my database, I want to turn off the validation for a model instance created within a given test example but *not* within my `before :each` ... So I need `expect_any_instance_of(MyModel)` to actually apply to *any* instance in this case, not exactly one instance ...

It makes me feel sad and a bit hurt that we keep calling it "code smell" when a lot of users want to test this type of situation.  I understand Rspec to be a general purpose code testing tool, and a very good one at that (thanks!  :-)), so it has to be able to test general purpose code.

I don't know how to get around this.  Any suggestions?  I know that I can do `save validate: false` but that feels hacky.  I really need Rspec to support this feature.  :-)

Have a nice weekend!

**Comment by JonRowe** [comment]
My suggestion would be `save validate: false`, it's basically designed for this use case.

**Comment by MaxPleaner** [comment]
Apologies for beating a dead horse, but

If I'm understanding correctly, the recommendation is to mock the instances so that the tests need to only refer to a single one. 

However, from what I've gathered, some people consider mocking to be a code smell as well.

Anyway, if anyone ends up reading this far through the issue, you can find a workaround here:

http://stackoverflow.com/questions/9800992/how-to-say-any-instance-should-receive-any-number-of-times-in-rspec
