### ISSUE TITLE
Method Stubs for alais_method

### ISSUE THREAD

**Issue by u2** [rspec/rspec-mocks#947]
There is a attribute named active_amount in `Account`.Now we want get `weijin_active_amount` when we call `active_amount`.
```ruby
class Account < ActiveRecord::Base
    alias_method :active_amount, :weijin_active_amount
end
```

```ruby
@account = create(:account, active_amount: Money.new(10000, 'CNY'))
allow(@account).to receive(:weijin_active_amount){ Money.new(50000, 'CNY') }
expect(@account.active_amount).to eq @account.weijin_active_amount #failed
```
I know when we `alias_method`, ruby copy the method to the new method.`allow(@account).to receive(:weijin_active_amount){ Money.new(50000, 'CNY') }`, it only change the `weijin_active_amount`, and the `active_amount` keep as before.

After mock this method, I do this,
```ruby
      class << @account
        alias_method :active_amount, :weijin_active_amount
      end
```
It passed, but it's ugly, I don't like this way.

So, it's possible that when we use `allow` check whether this method has aliased methods, and do `alias_method` in `allow` method.

**Comment by myronmarston** [comment]
> So, it's possible that when we use `allow` check whether this method has aliased methods, and do `alias_method` in `allow` method.

I don't think it is possible.  As far as I know, Ruby provides no APIs for telling you what method aliases exist.

If it was possible, I'm not sure it would be desirable; rspec-mocks focuses on _messages_ not _methods_, and even though `active_amount` and `weijin_active_amount` have identical implementations, they are different messages, and from that point of view, there's no reason rspec-mocks should treat them the same.

One solution for your case is to define `active_amount` to send the `weijin_active_amount` rather than defining an alias:

``` ruby
class Account < ActiveRecord::Base
  def active_amount
    weijin_active_amoung
  end 
end
```

When you use method aliasing, you are making a copy of that exact implementation, which specifically will _not_ stay up to date with the original method's implementation changes (such as if it was stubbed).  If you want them to stay up to date, then you should write it to delegate like this, and that should work for your case.

**Comment by u2** [comment]
Thanks for your detailed explanation, it make me clear  now.
